### ISSUE TITLE
Siprix Flutter Example: Working on IOS Simulator but not on Real Device

### ISSUE THREAD

**Issue by mars000** [siprix/FlutterPluginFederated#30]
I am compiling and running the example flutter app on IOS from directly from siprix github.
I initiate a video call from microSIP PC client (ext. 1004) to flutter app (ext. 1005).
**Scenario 1:** When I run flutter app on IOS Simulator it works ok. 
**Scenario 2:** When I run flutter app on IOS device the call comes through - I answer it but it  siprix flutter app stays stuck on "Accepting".

Logs below **Scenario 2** attached.
Any help would be appreciated.

[logs.txt](https://github.com/user-attachments/files/21769980/logs.txt)

**Comment by siprix** [comment]
Reason of issue in the second case:
 - enabled STUN takes long time to resolve public IP address
 - remote side sends CANCEL request 6sec after INVITE

We fixed this issue by sending SIP request/response just after collected candidates for preferred network interface.
You can test it using dev build from link below.
Download attached file, unzip and replace existing items in the folder: 
`$HOME/.pub-cache/hosted/pub.dev/siprix_voip_sdk_ios-1.0.19/ios`

[siprix_ios_20250815.zip](https://docs.siprix-voip.com/dn/siprix_ios_20250815.zip)

**Comment by mars000** [comment]
that worked thank you.
One other problem - i noticed that on Wifi (using IPv4 all is working), however if i switch to cellular network (5g) it does not work (as it switches to IPv6). Here are the logs:
```
-- LLDB integration loaded --
CLIENT OF UIKIT REQUIRES UPDATE: This process does not adopt UIScene lifecycle. This will become an assert in a future version.
FlutterView implements focusItemsInRect: - caching for linear focus movement is limited as long as this view is on screen.
flutter: The Dart VM service is listening on http://127.0.0.1:53554/OoPBln-47IA=/
flutter: _initializeSiprix
flutter: _readSavedState
App is being debugged, do not track this hang
Hang detected: 0.31s (debugger attached, not reporting)
190705.520 [1669932]  === Init: 2025-08-15 +1000 LogLevel File:1 Ide:2
190705.520 [1669932] (LogMessage.cpp:224): Darwin/localhost/24.6.0/Darwin Kernel Version 24.6.0: Tue Jul 15 21:54:57 PDT 2025; root:xnu-11417.140.69~16/RELEASE_ARM64_T8140/iPhone17,2
190705.520 [1669932] (SiprixModule.cpp:436): siprix: 1.0.19 from 20250815_0228
190705.520 [1670559] (audio_device_buffer.cc:66): AudioDeviceBuffer::ctor
190705.520 [1670559] (audio_device_impl.cc:143): current platform is IOS
190705.520 [1670559] (audio_device_impl.cc:159): CreatePlatformSpecificObjects
190705.520 [1670559] (audio_device_impl.cc:979): PlatformAudioLayer
190705.520 [1670559] (audio_device_ios.mm:107): AudioDeviceIOS::ctor<NSThread: 0x11885f400>{number = 13, name = (null)},bypass_voice_processing=0
190705.520 [1670559] (audio_device_impl.cc:288): iPhone Audio APIs will be utilized.
190705.520 [1670559] (audio_device_impl.cc:323): AttachAudioBuffer
190705.520 [1670559] (audio_device_ios.mm:124): AudioDeviceIOS::AttachAudioBuffer
190705.521 [1669932] (input_volume_stats_reporter.cc:87): Will not log any `WebRTC.Audio.Apm.AppliedInputVolume.*` histogram stats.
190705.521 [1669932] (input_volume_stats_reporter.cc:87): Will not log any `WebRTC.Audio.Apm.RecommendedInputVolume.*` histogram stats.
190705.521 [1669932] (audio_processing_impl.cc:299): Injected APM submodules:
Echo control factory: 0
Echo detector: 0
Capture analyzer: 0
Capture post processor: 0
Render pre processor: 0
190705.521 [1669932] (audio_processing_impl.cc:308): Denormal disabler: supported
190705.521 [1669932] (transient_suppressor_impl.cc:83): VAD mode: default
190705.521 [1669932] (webrtc_voice_engine.cc:313): WebRtcVoiceEngine::WebRtcVoiceEngine
190705.521 [1670559] (webrtc_voice_engine.cc:335): WebRtcVoiceEngine::Init
190705.521 [1670559] (audio_device_impl.cc:343): Init
190705.521 [1670559] (audio_device_ios.mm:131): AudioDeviceIOS::Init
190705.521 [1670559] (audio_device_ios.mm:637): AudioDeviceIOS::UpdateAudioDevicebuffer
190705.521 [1670559] (audio_device_buffer.cc:189): SetPlayoutSampleRate(48000)
190705.521 [1670559] (audio_device_buffer.cc:209): SetPlayoutChannels(1)
190705.521 [1670559] (audio_device_buffer.cc:183): SetRecordingSampleRate(48000)
190705.521 [1670559] (audio_device_buffer.cc:203): SetRecordingChannels(1)
190705.521 [1670559] (audio_device_impl.cc:687): SetPlayoutDevice(0)
190705.521 [1670559] (audio_device_ios.mm:1014): SetPlayoutDevice: Not implemented
190705.521 [1670559] (audio_device_impl.cc:376): InitSpeaker
190705.521 [1670559] (audio_device_impl.cc:591): StereoPlayoutIsAvailable
190705.521 [1670559] (audio_device_impl.cc:598): output: 0
190705.521 [1670559] (audio_device_impl.cc:603): SetStereoPlayout(0)
190705.521 [1670559] (audio_device_ios.mm:1067): SetStereoPlayout: Not implemented
190705.521 [1670559] (audio_device_impl.cc:611): stereo playout is not supported
190705.521 [1670559] (adm_helpers.cc:57): Failed to set stereo playout mode.
190705.521 [1670559] (audio_device_impl.cc:749): SetRecordingDevice(0)
190705.521 [1670559] (audio_device_ios.mm:1116): SetRecordingDevice: Not implemented
190705.521 [1670559] (audio_device_impl.cc:382): InitMicrophone
190705.521 [1670559] (audio_device_impl.cc:545): StereoRecordingIsAvailable
190705.521 [1670559] (audio_device_impl.cc:552): output: 0
190705.521 [1670559] (audio_device_impl.cc:557): SetStereoRecording(0)
190705.521 [1670559] (audio_device_ios.mm:1052): SetStereoRecording: Not implemented
190705.521 [1670559] (adm_helpers.cc:77): Failed to set stereo recording mode.
190705.521 [1670559] (audio_device_impl.cc:862): RegisterAudioCallback
190705.521 [1670559] (webrtc_voice_engine.cc:425): WebRtcVoiceEngine::ApplyOptions: AudioOptions {aec: 1, agc: 1, ns: 0, hf: 1, swap: 0, audio_jitter_buffer_max_packets: 200, audio_jitter_buffer_fast_accelerate: 0, audio_jitter_buffer_min_delay_ms: 0, }
190705.521 [1670559] (webrtc_voice_engine.cc:444): Always disable AEC on iOS. Use built-in instead.
190705.521 [1670559] (webrtc_voice_engine.cc:454): Always disable AGC on iOS. Use built-in instead.
190705.521 [1670559] (audio_device_impl.cc:878): BuiltInAECIsAvailable
190705.521 [1670559] (audio_device_generic.cc:18): BuiltInAECIsAvailable: Not supported on this platform
190705.521 [1670559] (audio_device_impl.cc:881): output: 0
190705.521 [1670559] (audio_device_impl.cc:894): BuiltInAGCIsAvailable
190705.521 [1670559] (audio_device_generic.cc:28): BuiltInAGCIsAvailable: Not supported on this platform
190705.521 [1670559] (audio_device_impl.cc:897): output: 0
190705.521 [1670559] (audio_device_impl.cc:910): BuiltInNSIsAvailable
190705.521 [1670559] (audio_device_generic.cc:38): BuiltInNSIsAvailable: Not supported on this platform
190705.521 [1670559] (audio_device_impl.cc:913): output: 0
190705.521 [1670559] (audio_processing_impl.cc:515): AudioProcessing::ApplyConfig: AudioProcessing::Config{ pipeline: { maximum_internal_processing_rate: 48000, multi_channel_render: 0, multi_channel_capture: 0 }, pre_amplifier: { enabled: 0, fixed_gain_factor: 1 },capture_level_adjustment: { enabled: 0, pre_gain_factor: 1, post_gain_factor: 1, analog_mic_gain_emulation: { enabled: 0, initial_level: 255 }}, high_pass_filter: { enabled: 1 }, echo_canceller: { enabled: 0, mobile_mode: 0, enforce_high_pass_filtering: 1 }, noise_suppression: { enabled: 0, level: High }, transient_suppression: { enabled: 1 }, gain_controller1: { enabled: 0, mode: FixedDigital, target_level_dbfs: 3, compression_gain_db: 9, enable_limiter: 1, analog_gain_controller { enabled: 1, startup_min_volume: 0, clipped_level_min: 70, enable_digital_adaptive: 1, clipped_level_step: 15, clipped_ratio_threshold: 0.1, clipped_wait_frames: 300, clipping_predictor:  { enabled: 0, mode: 0, window_length: 5, reference_window_length: 5, reference_window_delay: 5, clipping_threshold: -1, crest_factor_margin: 3, use_predicted_step: 1 }}}, gain_controller2: { enabled: 0, fixed_digital: { gain_db: 0 }, adaptive_digital: { enabled: 0, dry_run: 0, headroom_db: 6, max_gain_db: 30, initial_gain_db: 8, vad_reset_period_ms: 1500, adjacent_speech_frames_threshold: 12, max_gain_change_db_per_second: 3, max_output_noise_level_dbfs: -50 }, input_volume_control : { enabled 0}}
190705.521 [1669932] (rtc_peerconnection_factory_impl.cc:545): RtpSenderCaps: {codec:opus params:[48000 key:minptime val:10 key:useinbandfec val:1]} {codec:red params:[48000 key: val:111/111]} {codec:ISAC params:[16000]} {codec:ISAC params:[32000]} {codec:G722 params:[8000]} {codec:ILBC params:[8000]} {codec:PCMU params:[8000]} {codec:PCMA params:[8000]} {codec:CN params:[32000]} {codec:CN params:[16000]} {codec:CN params:[8000]} {codec:telephone-event params:[48000]} {codec:telephone-event params:[32000]} {codec:telephone-event params:[16000]} {codec:telephone-event params:[8000]} 
190705.521 [1669932] (rtc_peerconnection_factory_impl.cc:545): RtpSenderCaps: {codec:H264 params:[90000 key:level-asymmetry-allowed val:1 key:packetization-mode val:1 key:profile-level-id val:640c1f]} {codec:rtx params:[90000]} {codec:H264 params:[90000 key:level-asymmetry-allowed val:1 key:packetization-mode val:1 key:profile-level-id val:42e01f]} {codec:VP8 params:[90000]} {codec:VP9 params:[90000]} {codec:AV1 params:[90000]} {codec:red params:[90000]} {codec:ulpfec params:[90000]} 
190705.521 [1669932] (audio_device_impl.cc:952): SetAudioDeviceSink(18892648)
190705.521 [1669932] (audio_device_impl.cc:954): output: -1
190705.558 [1669932] (AresDns.cxx:397): DNS initialization: found  3 name servers
190705.558 [1669932] (AresDns.cxx:403):  name server: 2001:8004:2d43:900::
190705.558 [1669932] (AresDns.cxx:403):  name server: 2001:8004:2c42:91c::
190705.558 [1669932] (AresDns.cxx:408):  name server: 8.8.8.8
190705.558 [1669932] (Compression.cxx:46): Compression support not compiled in
190705.560 [1670602] (SiprixModule.cpp:489): Enter dumProcessingThread
190705.560 [1670470] (RTCNetworkMonitor.mm:115): Satisfied. Cellular IPv6
190705.560 [1670603] (Callbacks.cpp:361): Callback:32
190705.560 [1670603] (SiprixModule.cpp:1719): Reset network changed flag
190705.560 [1670603] (NetMonitorMac.mm:44): pdp_ip0-fe80::4b0:91dc:3814:862b; pdp_ip0-2001:8004:6bc1:14fb:41e:e8d:62ce:e211; pdp_ip0-2001:8004:6bc1:14fb:dd8c:57d0:450:9c13; pdp_ip1-fe80::ced:39cb:a6f4:c0c8; pdp_ip1-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; pdp_ip1-2001:8004:4d51:1e9c:492a:624e:d25b:f86f; ipsec1-fe80::c5c:502b:74d4:ddd5; anpi0-fe80::fc05:f5ff:fe93:4231; en2-fe80::cd4:ed3d:101d:4ff5; awdl0-fe80::5864:daff:fe21:d3d8; llw0-fe80::5864:daff:fe21:d3d8; ipsec6-fe80::c5c:502b:74d4:ddd5; ipsec6-fd74:6572:6d6e:7573:d:699c:3f40:2c8c; ipsec6-fd74:6572:6d6e:7573:c:699c:3f40:2c8c; ipsec7-fe80::c5c:502b:74d4:ddd5; ipsec7-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; ipsec8-fe80::c5c:502b:74d4:ddd5; ipsec8-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; 
flutter: writeAsset: '/var/mobile/Containers/Data/Application/8C331FB7-3352-4CF9-9418-81A9F7AED71C/Documents/ringtone.mp3' exists:true
flutter: Siprix module initialized successfully
flutter: Version: siprix: 1.0.19 from 20250815_0228
flutter: Adding new account: 1005@sip-test.net360.cloud
190705.576 [1669932] (UserProfile.cxx:103): Adding credential: realm=sip-test.net360.cloud user=1005
siprix: Ringtone path updated: '/var/mobile/Containers/Data/Application/8C331FB7-3352-4CF9-9418-81A9F7AED71C/Documents/ringtone.mp3'
190705.576 [1669932] (SiprixModule.cpp:676): Added account: 1005@sip-test.net360.cloud/103.115.115.25|48708 id:1
flutter: Added successfully with id: 1
190705.577 [1670602] (UserAgent.cxx:622): addTransportImpl: TLS/V6 port:48708 key:51
190705.577 [1670602] (Connection.cxx:45): Connection created fd=0
190705.577 [1670602] (ConnectionManager.cxx:34): ConnectionManager::ConnectionManager() called 
190705.577 [1670602] (TlsTransport.cxx:44): Creating TLS transport for domain  interface= port=48708
190705.577 [1670602] (DnsUtil.cxx:629): Considering: pdp_ip0 -> 192.0.0.2 flags=0x80d1
190705.577 [1670602] (DnsUtil.cxx:629): Considering: pdp_ip0 -> 192.0.0.2 flags=0x80d1
190705.577 [1670602] (DnsUtil.cxx:629): Considering: pdp_ip0 -> 192.0.0.2 flags=0x80d1
190705.577 [1670602] (DnsUtil.cxx:629): Considering: pdp_ip0 -> 192.0.0.2 flags=0x80d1
190705.577 [1670602] (DnsUtil.cxx:629): Considering: pdp_ip0 -> 192.0.0.2 flags=0x80d1
190705.577 [1670602] (DnsUtil.cxx:629): Considering: pdp_ip0 -> 192.0.0.2 flags=0x80d1
190705.578 [1670601] (TransportSelector.cxx:206): Adding transport: [:: port=48708 TLS]
190705.578 [1670601] (TransportSelector.cxx:278): added transport for tuple=[:: port=48708 TLS], key=51
190705.578 [1670602] (ClientRegistration.cxx:772): You really should consider setting an instance id in the UserProfile (see UserProfile::setInstanceId()). This is really easy, and makes this class much less likely to clash with another endpoint registering at the same AOR.
190705.578 [1670602] (RegistrationCreator.cxx:30): RegistrationCreator::RegistrationCreator: 0x10350f818
190705.578 [1670602] (DialogSet.cxx:54):  ************* Created DialogSet(UAC)  -- iV0ARMqhPNnvUXX2heEIhg..-f2664021*************
190705.578 [1670602] (DialogUsageManager.cxx:1123): Using outbound proxy: sips:103.115.115.25;transport=tls;lr -> SipReq:  REGISTER sip-test.net360.cloud tid=490bda2b0608d969 cseq=1 REGISTER contact=1005 / 1 from(tu)
190705.578 [1670602] (DialogUsageManager.cxx:1150): Sending to outbound uri
190705.578 [1670601] (DetermineSourceInterface.cxx:26): process 0x0
190705.578 [1670601] (TransportSelector.cxx:601): Looking up dns entries for sips:103.115.115.25;transport=tls;lr
190705.578 [1670601] (DnsResult.cxx:261): lookup: sips:103.115.115.25;transport=tls;lr
190705.578 [1670601] (TimerQueue.cxx:50): Adding timer: Timer F tid=490bda2b0608d969 ms=32000
190705.578 [1670601] (DnsResult.cxx:261): lookup: sips:103.115.115.25;transport=tls;lr
190705.579 [1670601] (DnsResult.cxx:333): Found immediate result: [103.115.115.25:5061 TLS targetDomain=103.115.115.25]
190705.579 [1670601] (DnsResult.cxx:333): Found immediate result: [103.115.115.25:5061 TLS targetDomain=103.115.115.25]
190705.579 [1670601] (DetermineSourceInterface.cxx:26): process 0x118984a00
190705.579 [1670601] (DetermineSourceInterface.cxx:54): determine src for target: [103.115.115.25:5061 TLS targetDomain=103.115.115.25]
190705.579 [1670601] (TransportSelector.cxx:802): Created routing socket4 key:51
190705.579 [1670601] (InternalTransport.cxx:121): Creating fd=33 V4/UDP
190705.579 [1670601] (DetermineSourceInterface.cxx:60): Success: [192.0.0.2:0 TLS targetDomain=103.115.115.25]
190705.579 [1670601] (TransportSelector.cxx:802): Created routing socket4 key:0
190705.579 [1670601] (InternalTransport.cxx:121): Creating fd=34 V4/UDP
190705.579 [1670601] (TransportSelector.cxx:1559): findTransportBySource([192.0.0.2:48708 TLS targetDomain=103.115.115.25])
190705.579 [1670601] (TransportSelector.cxx:1647): Can't find matching transport [192.0.0.2:48708 TLS targetDomain=103.115.115.25]
190705.579 [1670601] (TransportSelector.cxx:1361): tid=490bda2b0608d969 failed to find a transport to [103.115.115.25:5061 TLS targetDomain=103.115.115.25]
190705.579 [1670601] (TransactionState.cxx:2411): Try sending request to a different dns result
190705.579 [1670601] (TransactionState.cxx:2433): No DNS results remain.
190705.579 [1670601] (Helper.cxx:378): Helper::makeResponse(SipReq:  REGISTER sip-test.net360.cloud tid=490bda2b0608d969 cseq=1 REGISTER contact=1005 / 1 from(tu) code=503 reason=
190705.579 [1670601] (TransactionState.cxx:2237): Ran out of dns entries for 103.115.115.25. Send 503
190705.579 [1670601] (TuSelector.cxx:70): Send to TU: DialogUsageManager size=1
190705.579 [1670601] (DnsResult.cxx:187): Remove vip 103.115.115.25(1)
190705.580 [1670602] (UserAgent.cxx:1021): handleDetermineSrcInterface: 192.0.0.2 isSame:0 netSwitchMode:0
190705.580 [1670602] (DialogUsageManager.cxx:1625): Got: SipResp: 503 tid=490bda2b0608d969 cseq=1 REGISTER / 1 from(wire)
190705.580 [1670602] (DialogUsageManager.cxx:2234): DialogUsageManager::processResponse: SipResp: 503 tid=490bda2b0608d969 cseq=1 REGISTER / 1 from(wire)
190705.580 [1670602] (UserAgentRegistration.cxx:182): onRequestRetry(ClientRegistrationHandle): SipResp: 503 tid=490bda2b0608d969 cseq=1 REGISTER / 1 from(wire) ret:-1
190705.580 [1670602] (ClientRegistration.cxx:676): Application requested failure on Retry-After
190705.580 [1670602] (UserAgentRegistration.cxx:146): onFailure(ClientRegistrationHandle): SipResp: 503 tid=490bda2b0608d969 cseq=1 REGISTER / 1 from(wire) Ended:0
190705.580 [1670602] (TimerQueue.cxx:124): Adding application timer: DumTimeout::RegistrationRetry: duration=120 seq=1 ms=120000
190705.580 [1670602] (ClientRegistration.cxx:721): Registration error 503 for <sips:1005@sip-test.net360.cloud;transport=tls>;tag=b731155c, retrying in 120 seconds.
190705.580 [1670603] (Callbacks.cpp:180): Callback:30 accId:1 s:1
flutter: event OnAccountRegState {response: 503 No matching transport found, accId: 1, regState: 1}
flutter: onRegStateChanged accId:1 resp:'503 No matching transport found' RegState.failed
flutter: event OnTrialModeNotif {}
flutter: --- SIPRIX SDK is working in TRIAL mode ---
190706.851 [1670480] (RTCNetworkMonitor.mm:115): Satisfied. Cellular IPv6
190706.851 [1670603] (Callbacks.cpp:361): Callback:32
190706.851 [1670603] (SiprixModule.cpp:1719): Reset network changed flag
190706.852 [1670603] (NetMonitorMac.mm:44): pdp_ip0-fe80::4b0:91dc:3814:862b; pdp_ip0-2001:8004:6bc1:14fb:41e:e8d:62ce:e211; pdp_ip0-2001:8004:6bc1:14fb:dd8c:57d0:450:9c13; pdp_ip1-fe80::ced:39cb:a6f4:c0c8; pdp_ip1-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; pdp_ip1-2001:8004:4d51:1e9c:492a:624e:d25b:f86f; ipsec1-fe80::c5c:502b:74d4:ddd5; anpi0-fe80::fc05:f5ff:fe93:4231; en2-fe80::cd4:ed3d:101d:4ff5; awdl0-fe80::5864:daff:fe21:d3d8; llw0-fe80::5864:daff:fe21:d3d8; ipsec6-fe80::c5c:502b:74d4:ddd5; ipsec6-fd74:6572:6d6e:7573:d:699c:3f40:2c8c; ipsec6-fd74:6572:6d6e:7573:c:699c:3f40:2c8c; ipsec7-fe80::c5c:502b:74d4:ddd5; ipsec7-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; ipsec8-fe80::c5c:502b:74d4:ddd5; ipsec8-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; 
190715.248 [1670478] (RTCNetworkMonitor.mm:115): Satisfied. Cellular IPv6
190715.248 [1670603] (Callbacks.cpp:361): Callback:32
190715.248 [1670603] (SiprixModule.cpp:1719): Reset network changed flag
190715.248 [1670603] (NetMonitorMac.mm:44): pdp_ip0-fe80::4b0:91dc:3814:862b; pdp_ip0-2001:8004:6bc1:14fb:41e:e8d:62ce:e211; pdp_ip0-2001:8004:6bc1:14fb:dd8c:57d0:450:9c13; pdp_ip1-fe80::ced:39cb:a6f4:c0c8; pdp_ip1-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; pdp_ip1-2001:8004:4d51:1e9c:492a:624e:d25b:f86f; ipsec1-fe80::c5c:502b:74d4:ddd5; anpi0-fe80::fc05:f5ff:fe93:4231; en2-fe80::cd4:ed3d:101d:4ff5; awdl0-fe80::5864:daff:fe21:d3d8; llw0-fe80::5864:daff:fe21:d3d8; ipsec6-fe80::c5c:502b:74d4:ddd5; ipsec6-fd74:6572:6d6e:7573:d:699c:3f40:2c8c; ipsec6-fd74:6572:6d6e:7573:c:699c:3f40:2c8c; ipsec7-fe80::c5c:502b:74d4:ddd5; ipsec7-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; ipsec8-fe80::c5c:502b:74d4:ddd5; ipsec8-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; 
190719.446 [1670478] (RTCNetworkMonitor.mm:115): Satisfied. Cellular IPv6
190719.446 [1670603] (Callbacks.cpp:361): Callback:32
190719.446 [1670603] (SiprixModule.cpp:1719): Reset network changed flag
190719.446 [1670603] (NetMonitorMac.mm:44): pdp_ip0-fe80::4b0:91dc:3814:862b; pdp_ip0-2001:8004:6bc1:14fb:41e:e8d:62ce:e211; pdp_ip0-2001:8004:6bc1:14fb:dd8c:57d0:450:9c13; pdp_ip1-fe80::ced:39cb:a6f4:c0c8; pdp_ip1-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; pdp_ip1-2001:8004:4d51:1e9c:492a:624e:d25b:f86f; ipsec1-fe80::c5c:502b:74d4:ddd5; anpi0-fe80::fc05:f5ff:fe93:4231; en2-fe80::cd4:ed3d:101d:4ff5; awdl0-fe80::5864:daff:fe21:d3d8; llw0-fe80::5864:daff:fe21:d3d8; ipsec6-fe80::c5c:502b:74d4:ddd5; ipsec6-fd74:6572:6d6e:7573:d:699c:3f40:2c8c; ipsec6-fd74:6572:6d6e:7573:c:699c:3f40:2c8c; ipsec7-fe80::c5c:502b:74d4:ddd5; ipsec7-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; ipsec8-fe80::c5c:502b:74d4:ddd5; ipsec8-2001:8004:4d51:1e9c:9d:71bf:270f:1b19; 
```

**Comment by mars000** [comment]
> Reason of issue in the second case:
> 
> * enabled STUN takes long time to resolve public IP address
> * remote side sends CANCEL request 6sec after INVITE
> 
> We fixed this issue by sending SIP request/response just after collected candidates for preferred network interface. You can test it using dev build from link below. Download attached file, unzip and replace existing items in the folder: `$HOME/.pub-cache/hosted/pub.dev/siprix_voip_sdk_ios-1.0.19/ios`
> 
> [siprix_ios_20250815.zip](https://docs.siprix-voip.com/dn/siprix_ios_20250815.zip)

I tried on Android with same problem - do you need to provide update zip for Android as well please ?

**Comment by mars000** [comment]
> We'll publish updated version for all platforms today.
> 
> Regarding "it does not work as it switches to IPv6" - library uses `nw_path_monitor` for detecting network changes and list of available network interfaces. When device connected to 5g the following steps processed:
> 
> * net monitor reports that available only IPv6
> * library creates IPv6 transport
> * app provided IPv4 address of the server
> * library can't reach IPv4 server from IPv6.
>   If app would specify domain name of the server (instead of IP address), it resolved to IPv6 by DNS64 and connection was possible.
> 
> In the same time low level impl detected IP address '192.0.0.2', which missed in the list reported by NetMonitor (it uses [nw_path_has_ipv4](https://developer.apple.com/documentation/network/nw_path_has_ipv4(_:)?language=objc)):
> 
> ```
> bool hasIPv4 = nw_path_has_ipv4(path);
> bool hasIPv6 = nw_path_has_ipv6(path);
> ```
> 
> Here is updated dev build with following temporary fix: ignore `hasIPv4` and always force using IPv4 interface. Can you plz update and check behavior in the same environment? [siprix_ios_20250816.zip](https://docs.siprix-voip.com/dn/siprix_ios_20250816.zip)

Hello, and thank you for the fix - i can confirm it now works on WiFi and 5G (see logs attached which show initial call on WiFi and second call on 5G).
I am have one minor problem still - when I initiate a video call from siprix app to another SIP device audio and video work fine, but when I receive a call to mobile siprix app only Video comes through, i do not hear any audio on either device. Any clues from logs as to why that might be the case ?

[logs_ipv6_test.txt](https://github.com/user-attachments/files/21820705/logs_ipv6_test.txt)

**Comment by mars000** [comment]
> It's known limitation. When (any) iOS app goes to background it not only stops working, but also loses access to network. It can wake up only if user manually starts it or push notif received.
> 
> When app is working on device connected to computer it appears that everything works good, but try to check the same case without USB cable connection.

would using a SIP Proxy e.g. FlexiSIP solve that problem ?
